name: Copy to Server

on:
  workflow_dispatch: # Ручной запуск через интерфейс GitHub Actions
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

#    - name: Setup SSH key
#      env:
#        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
#      run: |
#        mkdir -p ~/.ssh
#        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
#        chmod 600 ~/.ssh/id_rsa

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

#    - name: Copy repository to server
#      run: |
#        rsync -avz --delete \
#          --exclude='.git' \
#          --exclude='.env' \
#          --exclude='.env.example' \
#          --exclude='.gitignore' \
#          --exclude='docker-compose.db.yml' \
#          --exclude='.github/' \
#          --exclude='data/' \
#          ./ \
#          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/movies-x-point/

    - name: Copy files to server
      run: |
        scp -r ./ horse@5.35.124.148:/home/horse/movies-x-point